name: simple tests run with Firefox

on: [workflow_dispatch]

jobs:
  tests:
    runs-on: ubuntu-22.04
    # https://github.com/cypress-io/cypress-docker-images
    container: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: npm run prod:run
        uses: cypress-io/github-action@v6
        timeout-minutes: 10
        with:
          browser: firefox
