name: Cypress simple tests run on Edge

on: [workflow_dispatch]

jobs:
  tests:
    runs-on: ubuntu-22.04
    # https://github.com/cypress-io/cypress-docker-images
    container: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
#
#      - uses: browser-actions/setup-firefox@v1
#      - run: firefox --version

      - name: npm run prod:run
        uses: cypress-io/github-action@v6
        timeout-minutes: 10
        with:
          browser: edge
